package com.zcjd.app_server.model;

import java.util.ArrayList;
import java.util.List;

public class AttendanceSetPojoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hr_attendance_set
     *
     * @mbg.generated Thu Sep 19 10:13:33 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hr_attendance_set
     *
     * @mbg.generated Thu Sep 19 10:13:33 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hr_attendance_set
     *
     * @mbg.generated Thu Sep 19 10:13:33 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_attendance_set
     *
     * @mbg.generated Thu Sep 19 10:13:33 CST 2019
     */
    public AttendanceSetPojoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_attendance_set
     *
     * @mbg.generated Thu Sep 19 10:13:33 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_attendance_set
     *
     * @mbg.generated Thu Sep 19 10:13:33 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_attendance_set
     *
     * @mbg.generated Thu Sep 19 10:13:33 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_attendance_set
     *
     * @mbg.generated Thu Sep 19 10:13:33 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_attendance_set
     *
     * @mbg.generated Thu Sep 19 10:13:33 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_attendance_set
     *
     * @mbg.generated Thu Sep 19 10:13:33 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_attendance_set
     *
     * @mbg.generated Thu Sep 19 10:13:33 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_attendance_set
     *
     * @mbg.generated Thu Sep 19 10:13:33 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_attendance_set
     *
     * @mbg.generated Thu Sep 19 10:13:33 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_attendance_set
     *
     * @mbg.generated Thu Sep 19 10:13:33 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hr_attendance_set
     *
     * @mbg.generated Thu Sep 19 10:13:33 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andWorkStartTimeIsNull() {
            addCriterion("work_start_time is null");
            return (Criteria) this;
        }

        public Criteria andWorkStartTimeIsNotNull() {
            addCriterion("work_start_time is not null");
            return (Criteria) this;
        }

        public Criteria andWorkStartTimeEqualTo(String value) {
            addCriterion("work_start_time =", value, "workStartTime");
            return (Criteria) this;
        }

        public Criteria andWorkStartTimeNotEqualTo(String value) {
            addCriterion("work_start_time <>", value, "workStartTime");
            return (Criteria) this;
        }

        public Criteria andWorkStartTimeGreaterThan(String value) {
            addCriterion("work_start_time >", value, "workStartTime");
            return (Criteria) this;
        }

        public Criteria andWorkStartTimeGreaterThanOrEqualTo(String value) {
            addCriterion("work_start_time >=", value, "workStartTime");
            return (Criteria) this;
        }

        public Criteria andWorkStartTimeLessThan(String value) {
            addCriterion("work_start_time <", value, "workStartTime");
            return (Criteria) this;
        }

        public Criteria andWorkStartTimeLessThanOrEqualTo(String value) {
            addCriterion("work_start_time <=", value, "workStartTime");
            return (Criteria) this;
        }

        public Criteria andWorkStartTimeLike(String value) {
            addCriterion("work_start_time like", value, "workStartTime");
            return (Criteria) this;
        }

        public Criteria andWorkStartTimeNotLike(String value) {
            addCriterion("work_start_time not like", value, "workStartTime");
            return (Criteria) this;
        }

        public Criteria andWorkStartTimeIn(List<String> values) {
            addCriterion("work_start_time in", values, "workStartTime");
            return (Criteria) this;
        }

        public Criteria andWorkStartTimeNotIn(List<String> values) {
            addCriterion("work_start_time not in", values, "workStartTime");
            return (Criteria) this;
        }

        public Criteria andWorkStartTimeBetween(String value1, String value2) {
            addCriterion("work_start_time between", value1, value2, "workStartTime");
            return (Criteria) this;
        }

        public Criteria andWorkStartTimeNotBetween(String value1, String value2) {
            addCriterion("work_start_time not between", value1, value2, "workStartTime");
            return (Criteria) this;
        }

        public Criteria andWorkDayIsNull() {
            addCriterion("work_day is null");
            return (Criteria) this;
        }

        public Criteria andWorkDayIsNotNull() {
            addCriterion("work_day is not null");
            return (Criteria) this;
        }

        public Criteria andWorkDayEqualTo(String value) {
            addCriterion("work_day =", value, "workDay");
            return (Criteria) this;
        }

        public Criteria andWorkDayNotEqualTo(String value) {
            addCriterion("work_day <>", value, "workDay");
            return (Criteria) this;
        }

        public Criteria andWorkDayGreaterThan(String value) {
            addCriterion("work_day >", value, "workDay");
            return (Criteria) this;
        }

        public Criteria andWorkDayGreaterThanOrEqualTo(String value) {
            addCriterion("work_day >=", value, "workDay");
            return (Criteria) this;
        }

        public Criteria andWorkDayLessThan(String value) {
            addCriterion("work_day <", value, "workDay");
            return (Criteria) this;
        }

        public Criteria andWorkDayLessThanOrEqualTo(String value) {
            addCriterion("work_day <=", value, "workDay");
            return (Criteria) this;
        }

        public Criteria andWorkDayLike(String value) {
            addCriterion("work_day like", value, "workDay");
            return (Criteria) this;
        }

        public Criteria andWorkDayNotLike(String value) {
            addCriterion("work_day not like", value, "workDay");
            return (Criteria) this;
        }

        public Criteria andWorkDayIn(List<String> values) {
            addCriterion("work_day in", values, "workDay");
            return (Criteria) this;
        }

        public Criteria andWorkDayNotIn(List<String> values) {
            addCriterion("work_day not in", values, "workDay");
            return (Criteria) this;
        }

        public Criteria andWorkDayBetween(String value1, String value2) {
            addCriterion("work_day between", value1, value2, "workDay");
            return (Criteria) this;
        }

        public Criteria andWorkDayNotBetween(String value1, String value2) {
            addCriterion("work_day not between", value1, value2, "workDay");
            return (Criteria) this;
        }

        public Criteria andCountIsNull() {
            addCriterion("count is null");
            return (Criteria) this;
        }

        public Criteria andCountIsNotNull() {
            addCriterion("count is not null");
            return (Criteria) this;
        }

        public Criteria andCountEqualTo(Integer value) {
            addCriterion("count =", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotEqualTo(Integer value) {
            addCriterion("count <>", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountGreaterThan(Integer value) {
            addCriterion("count >", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("count >=", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountLessThan(Integer value) {
            addCriterion("count <", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountLessThanOrEqualTo(Integer value) {
            addCriterion("count <=", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountIn(List<Integer> values) {
            addCriterion("count in", values, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotIn(List<Integer> values) {
            addCriterion("count not in", values, "count");
            return (Criteria) this;
        }

        public Criteria andCountBetween(Integer value1, Integer value2) {
            addCriterion("count between", value1, value2, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotBetween(Integer value1, Integer value2) {
            addCriterion("count not between", value1, value2, "count");
            return (Criteria) this;
        }

        public Criteria andWorkTimeIsNull() {
            addCriterion("work_time is null");
            return (Criteria) this;
        }

        public Criteria andWorkTimeIsNotNull() {
            addCriterion("work_time is not null");
            return (Criteria) this;
        }

        public Criteria andWorkTimeEqualTo(String value) {
            addCriterion("work_time =", value, "workTime");
            return (Criteria) this;
        }

        public Criteria andWorkTimeNotEqualTo(String value) {
            addCriterion("work_time <>", value, "workTime");
            return (Criteria) this;
        }

        public Criteria andWorkTimeGreaterThan(String value) {
            addCriterion("work_time >", value, "workTime");
            return (Criteria) this;
        }

        public Criteria andWorkTimeGreaterThanOrEqualTo(String value) {
            addCriterion("work_time >=", value, "workTime");
            return (Criteria) this;
        }

        public Criteria andWorkTimeLessThan(String value) {
            addCriterion("work_time <", value, "workTime");
            return (Criteria) this;
        }

        public Criteria andWorkTimeLessThanOrEqualTo(String value) {
            addCriterion("work_time <=", value, "workTime");
            return (Criteria) this;
        }

        public Criteria andWorkTimeLike(String value) {
            addCriterion("work_time like", value, "workTime");
            return (Criteria) this;
        }

        public Criteria andWorkTimeNotLike(String value) {
            addCriterion("work_time not like", value, "workTime");
            return (Criteria) this;
        }

        public Criteria andWorkTimeIn(List<String> values) {
            addCriterion("work_time in", values, "workTime");
            return (Criteria) this;
        }

        public Criteria andWorkTimeNotIn(List<String> values) {
            addCriterion("work_time not in", values, "workTime");
            return (Criteria) this;
        }

        public Criteria andWorkTimeBetween(String value1, String value2) {
            addCriterion("work_time between", value1, value2, "workTime");
            return (Criteria) this;
        }

        public Criteria andWorkTimeNotBetween(String value1, String value2) {
            addCriterion("work_time not between", value1, value2, "workTime");
            return (Criteria) this;
        }

        public Criteria andAfterTimeIsNull() {
            addCriterion("after_time is null");
            return (Criteria) this;
        }

        public Criteria andAfterTimeIsNotNull() {
            addCriterion("after_time is not null");
            return (Criteria) this;
        }

        public Criteria andAfterTimeEqualTo(String value) {
            addCriterion("after_time =", value, "afterTime");
            return (Criteria) this;
        }

        public Criteria andAfterTimeNotEqualTo(String value) {
            addCriterion("after_time <>", value, "afterTime");
            return (Criteria) this;
        }

        public Criteria andAfterTimeGreaterThan(String value) {
            addCriterion("after_time >", value, "afterTime");
            return (Criteria) this;
        }

        public Criteria andAfterTimeGreaterThanOrEqualTo(String value) {
            addCriterion("after_time >=", value, "afterTime");
            return (Criteria) this;
        }

        public Criteria andAfterTimeLessThan(String value) {
            addCriterion("after_time <", value, "afterTime");
            return (Criteria) this;
        }

        public Criteria andAfterTimeLessThanOrEqualTo(String value) {
            addCriterion("after_time <=", value, "afterTime");
            return (Criteria) this;
        }

        public Criteria andAfterTimeLike(String value) {
            addCriterion("after_time like", value, "afterTime");
            return (Criteria) this;
        }

        public Criteria andAfterTimeNotLike(String value) {
            addCriterion("after_time not like", value, "afterTime");
            return (Criteria) this;
        }

        public Criteria andAfterTimeIn(List<String> values) {
            addCriterion("after_time in", values, "afterTime");
            return (Criteria) this;
        }

        public Criteria andAfterTimeNotIn(List<String> values) {
            addCriterion("after_time not in", values, "afterTime");
            return (Criteria) this;
        }

        public Criteria andAfterTimeBetween(String value1, String value2) {
            addCriterion("after_time between", value1, value2, "afterTime");
            return (Criteria) this;
        }

        public Criteria andAfterTimeNotBetween(String value1, String value2) {
            addCriterion("after_time not between", value1, value2, "afterTime");
            return (Criteria) this;
        }

        public Criteria andWorkEndTimeIsNull() {
            addCriterion("work_end_time is null");
            return (Criteria) this;
        }

        public Criteria andWorkEndTimeIsNotNull() {
            addCriterion("work_end_time is not null");
            return (Criteria) this;
        }

        public Criteria andWorkEndTimeEqualTo(String value) {
            addCriterion("work_end_time =", value, "workEndTime");
            return (Criteria) this;
        }

        public Criteria andWorkEndTimeNotEqualTo(String value) {
            addCriterion("work_end_time <>", value, "workEndTime");
            return (Criteria) this;
        }

        public Criteria andWorkEndTimeGreaterThan(String value) {
            addCriterion("work_end_time >", value, "workEndTime");
            return (Criteria) this;
        }

        public Criteria andWorkEndTimeGreaterThanOrEqualTo(String value) {
            addCriterion("work_end_time >=", value, "workEndTime");
            return (Criteria) this;
        }

        public Criteria andWorkEndTimeLessThan(String value) {
            addCriterion("work_end_time <", value, "workEndTime");
            return (Criteria) this;
        }

        public Criteria andWorkEndTimeLessThanOrEqualTo(String value) {
            addCriterion("work_end_time <=", value, "workEndTime");
            return (Criteria) this;
        }

        public Criteria andWorkEndTimeLike(String value) {
            addCriterion("work_end_time like", value, "workEndTime");
            return (Criteria) this;
        }

        public Criteria andWorkEndTimeNotLike(String value) {
            addCriterion("work_end_time not like", value, "workEndTime");
            return (Criteria) this;
        }

        public Criteria andWorkEndTimeIn(List<String> values) {
            addCriterion("work_end_time in", values, "workEndTime");
            return (Criteria) this;
        }

        public Criteria andWorkEndTimeNotIn(List<String> values) {
            addCriterion("work_end_time not in", values, "workEndTime");
            return (Criteria) this;
        }

        public Criteria andWorkEndTimeBetween(String value1, String value2) {
            addCriterion("work_end_time between", value1, value2, "workEndTime");
            return (Criteria) this;
        }

        public Criteria andWorkEndTimeNotBetween(String value1, String value2) {
            addCriterion("work_end_time not between", value1, value2, "workEndTime");
            return (Criteria) this;
        }

        public Criteria andAfterStartTimeIsNull() {
            addCriterion("after_start_time is null");
            return (Criteria) this;
        }

        public Criteria andAfterStartTimeIsNotNull() {
            addCriterion("after_start_time is not null");
            return (Criteria) this;
        }

        public Criteria andAfterStartTimeEqualTo(String value) {
            addCriterion("after_start_time =", value, "afterStartTime");
            return (Criteria) this;
        }

        public Criteria andAfterStartTimeNotEqualTo(String value) {
            addCriterion("after_start_time <>", value, "afterStartTime");
            return (Criteria) this;
        }

        public Criteria andAfterStartTimeGreaterThan(String value) {
            addCriterion("after_start_time >", value, "afterStartTime");
            return (Criteria) this;
        }

        public Criteria andAfterStartTimeGreaterThanOrEqualTo(String value) {
            addCriterion("after_start_time >=", value, "afterStartTime");
            return (Criteria) this;
        }

        public Criteria andAfterStartTimeLessThan(String value) {
            addCriterion("after_start_time <", value, "afterStartTime");
            return (Criteria) this;
        }

        public Criteria andAfterStartTimeLessThanOrEqualTo(String value) {
            addCriterion("after_start_time <=", value, "afterStartTime");
            return (Criteria) this;
        }

        public Criteria andAfterStartTimeLike(String value) {
            addCriterion("after_start_time like", value, "afterStartTime");
            return (Criteria) this;
        }

        public Criteria andAfterStartTimeNotLike(String value) {
            addCriterion("after_start_time not like", value, "afterStartTime");
            return (Criteria) this;
        }

        public Criteria andAfterStartTimeIn(List<String> values) {
            addCriterion("after_start_time in", values, "afterStartTime");
            return (Criteria) this;
        }

        public Criteria andAfterStartTimeNotIn(List<String> values) {
            addCriterion("after_start_time not in", values, "afterStartTime");
            return (Criteria) this;
        }

        public Criteria andAfterStartTimeBetween(String value1, String value2) {
            addCriterion("after_start_time between", value1, value2, "afterStartTime");
            return (Criteria) this;
        }

        public Criteria andAfterStartTimeNotBetween(String value1, String value2) {
            addCriterion("after_start_time not between", value1, value2, "afterStartTime");
            return (Criteria) this;
        }

        public Criteria andAfterEndTimeIsNull() {
            addCriterion("after_end_time is null");
            return (Criteria) this;
        }

        public Criteria andAfterEndTimeIsNotNull() {
            addCriterion("after_end_time is not null");
            return (Criteria) this;
        }

        public Criteria andAfterEndTimeEqualTo(String value) {
            addCriterion("after_end_time =", value, "afterEndTime");
            return (Criteria) this;
        }

        public Criteria andAfterEndTimeNotEqualTo(String value) {
            addCriterion("after_end_time <>", value, "afterEndTime");
            return (Criteria) this;
        }

        public Criteria andAfterEndTimeGreaterThan(String value) {
            addCriterion("after_end_time >", value, "afterEndTime");
            return (Criteria) this;
        }

        public Criteria andAfterEndTimeGreaterThanOrEqualTo(String value) {
            addCriterion("after_end_time >=", value, "afterEndTime");
            return (Criteria) this;
        }

        public Criteria andAfterEndTimeLessThan(String value) {
            addCriterion("after_end_time <", value, "afterEndTime");
            return (Criteria) this;
        }

        public Criteria andAfterEndTimeLessThanOrEqualTo(String value) {
            addCriterion("after_end_time <=", value, "afterEndTime");
            return (Criteria) this;
        }

        public Criteria andAfterEndTimeLike(String value) {
            addCriterion("after_end_time like", value, "afterEndTime");
            return (Criteria) this;
        }

        public Criteria andAfterEndTimeNotLike(String value) {
            addCriterion("after_end_time not like", value, "afterEndTime");
            return (Criteria) this;
        }

        public Criteria andAfterEndTimeIn(List<String> values) {
            addCriterion("after_end_time in", values, "afterEndTime");
            return (Criteria) this;
        }

        public Criteria andAfterEndTimeNotIn(List<String> values) {
            addCriterion("after_end_time not in", values, "afterEndTime");
            return (Criteria) this;
        }

        public Criteria andAfterEndTimeBetween(String value1, String value2) {
            addCriterion("after_end_time between", value1, value2, "afterEndTime");
            return (Criteria) this;
        }

        public Criteria andAfterEndTimeNotBetween(String value1, String value2) {
            addCriterion("after_end_time not between", value1, value2, "afterEndTime");
            return (Criteria) this;
        }

        public Criteria andAttendanceDayIsNull() {
            addCriterion("attendance_day is null");
            return (Criteria) this;
        }

        public Criteria andAttendanceDayIsNotNull() {
            addCriterion("attendance_day is not null");
            return (Criteria) this;
        }

        public Criteria andAttendanceDayEqualTo(Integer value) {
            addCriterion("attendance_day =", value, "attendanceDay");
            return (Criteria) this;
        }

        public Criteria andAttendanceDayNotEqualTo(Integer value) {
            addCriterion("attendance_day <>", value, "attendanceDay");
            return (Criteria) this;
        }

        public Criteria andAttendanceDayGreaterThan(Integer value) {
            addCriterion("attendance_day >", value, "attendanceDay");
            return (Criteria) this;
        }

        public Criteria andAttendanceDayGreaterThanOrEqualTo(Integer value) {
            addCriterion("attendance_day >=", value, "attendanceDay");
            return (Criteria) this;
        }

        public Criteria andAttendanceDayLessThan(Integer value) {
            addCriterion("attendance_day <", value, "attendanceDay");
            return (Criteria) this;
        }

        public Criteria andAttendanceDayLessThanOrEqualTo(Integer value) {
            addCriterion("attendance_day <=", value, "attendanceDay");
            return (Criteria) this;
        }

        public Criteria andAttendanceDayIn(List<Integer> values) {
            addCriterion("attendance_day in", values, "attendanceDay");
            return (Criteria) this;
        }

        public Criteria andAttendanceDayNotIn(List<Integer> values) {
            addCriterion("attendance_day not in", values, "attendanceDay");
            return (Criteria) this;
        }

        public Criteria andAttendanceDayBetween(Integer value1, Integer value2) {
            addCriterion("attendance_day between", value1, value2, "attendanceDay");
            return (Criteria) this;
        }

        public Criteria andAttendanceDayNotBetween(Integer value1, Integer value2) {
            addCriterion("attendance_day not between", value1, value2, "attendanceDay");
            return (Criteria) this;
        }

        public Criteria andDeleteStateIsNull() {
            addCriterion("delete_state is null");
            return (Criteria) this;
        }

        public Criteria andDeleteStateIsNotNull() {
            addCriterion("delete_state is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteStateEqualTo(Integer value) {
            addCriterion("delete_state =", value, "deleteState");
            return (Criteria) this;
        }

        public Criteria andDeleteStateNotEqualTo(Integer value) {
            addCriterion("delete_state <>", value, "deleteState");
            return (Criteria) this;
        }

        public Criteria andDeleteStateGreaterThan(Integer value) {
            addCriterion("delete_state >", value, "deleteState");
            return (Criteria) this;
        }

        public Criteria andDeleteStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("delete_state >=", value, "deleteState");
            return (Criteria) this;
        }

        public Criteria andDeleteStateLessThan(Integer value) {
            addCriterion("delete_state <", value, "deleteState");
            return (Criteria) this;
        }

        public Criteria andDeleteStateLessThanOrEqualTo(Integer value) {
            addCriterion("delete_state <=", value, "deleteState");
            return (Criteria) this;
        }

        public Criteria andDeleteStateIn(List<Integer> values) {
            addCriterion("delete_state in", values, "deleteState");
            return (Criteria) this;
        }

        public Criteria andDeleteStateNotIn(List<Integer> values) {
            addCriterion("delete_state not in", values, "deleteState");
            return (Criteria) this;
        }

        public Criteria andDeleteStateBetween(Integer value1, Integer value2) {
            addCriterion("delete_state between", value1, value2, "deleteState");
            return (Criteria) this;
        }

        public Criteria andDeleteStateNotBetween(Integer value1, Integer value2) {
            addCriterion("delete_state not between", value1, value2, "deleteState");
            return (Criteria) this;
        }

        public Criteria andMaplngIsNull() {
            addCriterion("maplng is null");
            return (Criteria) this;
        }

        public Criteria andMaplngIsNotNull() {
            addCriterion("maplng is not null");
            return (Criteria) this;
        }

        public Criteria andMaplngEqualTo(String value) {
            addCriterion("maplng =", value, "maplng");
            return (Criteria) this;
        }

        public Criteria andMaplngNotEqualTo(String value) {
            addCriterion("maplng <>", value, "maplng");
            return (Criteria) this;
        }

        public Criteria andMaplngGreaterThan(String value) {
            addCriterion("maplng >", value, "maplng");
            return (Criteria) this;
        }

        public Criteria andMaplngGreaterThanOrEqualTo(String value) {
            addCriterion("maplng >=", value, "maplng");
            return (Criteria) this;
        }

        public Criteria andMaplngLessThan(String value) {
            addCriterion("maplng <", value, "maplng");
            return (Criteria) this;
        }

        public Criteria andMaplngLessThanOrEqualTo(String value) {
            addCriterion("maplng <=", value, "maplng");
            return (Criteria) this;
        }

        public Criteria andMaplngLike(String value) {
            addCriterion("maplng like", value, "maplng");
            return (Criteria) this;
        }

        public Criteria andMaplngNotLike(String value) {
            addCriterion("maplng not like", value, "maplng");
            return (Criteria) this;
        }

        public Criteria andMaplngIn(List<String> values) {
            addCriterion("maplng in", values, "maplng");
            return (Criteria) this;
        }

        public Criteria andMaplngNotIn(List<String> values) {
            addCriterion("maplng not in", values, "maplng");
            return (Criteria) this;
        }

        public Criteria andMaplngBetween(String value1, String value2) {
            addCriterion("maplng between", value1, value2, "maplng");
            return (Criteria) this;
        }

        public Criteria andMaplngNotBetween(String value1, String value2) {
            addCriterion("maplng not between", value1, value2, "maplng");
            return (Criteria) this;
        }

        public Criteria andMaplatIsNull() {
            addCriterion("maplat is null");
            return (Criteria) this;
        }

        public Criteria andMaplatIsNotNull() {
            addCriterion("maplat is not null");
            return (Criteria) this;
        }

        public Criteria andMaplatEqualTo(String value) {
            addCriterion("maplat =", value, "maplat");
            return (Criteria) this;
        }

        public Criteria andMaplatNotEqualTo(String value) {
            addCriterion("maplat <>", value, "maplat");
            return (Criteria) this;
        }

        public Criteria andMaplatGreaterThan(String value) {
            addCriterion("maplat >", value, "maplat");
            return (Criteria) this;
        }

        public Criteria andMaplatGreaterThanOrEqualTo(String value) {
            addCriterion("maplat >=", value, "maplat");
            return (Criteria) this;
        }

        public Criteria andMaplatLessThan(String value) {
            addCriterion("maplat <", value, "maplat");
            return (Criteria) this;
        }

        public Criteria andMaplatLessThanOrEqualTo(String value) {
            addCriterion("maplat <=", value, "maplat");
            return (Criteria) this;
        }

        public Criteria andMaplatLike(String value) {
            addCriterion("maplat like", value, "maplat");
            return (Criteria) this;
        }

        public Criteria andMaplatNotLike(String value) {
            addCriterion("maplat not like", value, "maplat");
            return (Criteria) this;
        }

        public Criteria andMaplatIn(List<String> values) {
            addCriterion("maplat in", values, "maplat");
            return (Criteria) this;
        }

        public Criteria andMaplatNotIn(List<String> values) {
            addCriterion("maplat not in", values, "maplat");
            return (Criteria) this;
        }

        public Criteria andMaplatBetween(String value1, String value2) {
            addCriterion("maplat between", value1, value2, "maplat");
            return (Criteria) this;
        }

        public Criteria andMaplatNotBetween(String value1, String value2) {
            addCriterion("maplat not between", value1, value2, "maplat");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hr_attendance_set
     *
     * @mbg.generated do_not_delete_during_merge Thu Sep 19 10:13:33 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hr_attendance_set
     *
     * @mbg.generated Thu Sep 19 10:13:33 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}