package com.zcjd.app_server.model;

public class DeptContact {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_contact.id
     *
     * @mbg.generated Thu Aug 29 09:41:12 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_contact.user_id
     *
     * @mbg.generated Thu Aug 29 09:41:12 CST 2019
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_contact.contact_user_id
     *
     * @mbg.generated Thu Aug 29 09:41:12 CST 2019
     */
    private String contactUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_contact.id
     *
     * @return the value of app_contact.id
     *
     * @mbg.generated Thu Aug 29 09:41:12 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_contact.id
     *
     * @param id the value for app_contact.id
     *
     * @mbg.generated Thu Aug 29 09:41:12 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_contact.user_id
     *
     * @return the value of app_contact.user_id
     *
     * @mbg.generated Thu Aug 29 09:41:12 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_contact.user_id
     *
     * @param userId the value for app_contact.user_id
     *
     * @mbg.generated Thu Aug 29 09:41:12 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_contact.contact_user_id
     *
     * @return the value of app_contact.contact_user_id
     *
     * @mbg.generated Thu Aug 29 09:41:12 CST 2019
     */
    public String getContactUserId() {
        return contactUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_contact.contact_user_id
     *
     * @param contactUserId the value for app_contact.contact_user_id
     *
     * @mbg.generated Thu Aug 29 09:41:12 CST 2019
     */
    public void setContactUserId(String contactUserId) {
        this.contactUserId = contactUserId == null ? null : contactUserId.trim();
    }
}