package com.zcjd.app_server.mapper;

import java.util.List;

import com.zcjd.app_server.model.AttendanceSetPojo;
import com.zcjd.app_server.model.AttendanceSetPojoExample;
import com.zcjd.app_server.model.AttendanceSetPojoKey;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface AttendanceSetPojoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_attendance_set
     *
     * @mbg.generated Thu Sep 19 10:13:33 CST 2019
     */
    long countByExample(AttendanceSetPojoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_attendance_set
     *
     * @mbg.generated Thu Sep 19 10:13:33 CST 2019
     */
    int deleteByExample(AttendanceSetPojoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_attendance_set
     *
     * @mbg.generated Thu Sep 19 10:13:33 CST 2019
     */
    int deleteByPrimaryKey(AttendanceSetPojoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_attendance_set
     *
     * @mbg.generated Thu Sep 19 10:13:33 CST 2019
     */
    int insert(AttendanceSetPojo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_attendance_set
     *
     * @mbg.generated Thu Sep 19 10:13:33 CST 2019
     */
    int insertSelective(AttendanceSetPojo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_attendance_set
     *
     * @mbg.generated Thu Sep 19 10:13:33 CST 2019
     */
    List<AttendanceSetPojo> selectByExample(AttendanceSetPojoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_attendance_set
     *
     * @mbg.generated Thu Sep 19 10:13:33 CST 2019
     */
    AttendanceSetPojo selectByPrimaryKey(AttendanceSetPojoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_attendance_set
     *
     * @mbg.generated Thu Sep 19 10:13:33 CST 2019
     */
    int updateByExampleSelective(@Param("record") AttendanceSetPojo record, @Param("example") AttendanceSetPojoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_attendance_set
     *
     * @mbg.generated Thu Sep 19 10:13:33 CST 2019
     */
    int updateByExample(@Param("record") AttendanceSetPojo record, @Param("example") AttendanceSetPojoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_attendance_set
     *
     * @mbg.generated Thu Sep 19 10:13:33 CST 2019
     */
    int updateByPrimaryKeySelective(AttendanceSetPojo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hr_attendance_set
     *
     * @mbg.generated Thu Sep 19 10:13:33 CST 2019
     */
    int updateByPrimaryKey(AttendanceSetPojo record);

    /**
     * 根据日程规划查询日期考勤规划
     * @param week 当前日期
     * @return
     * @throws Exception
     */
     AttendanceSetPojo selectWeek(int week);
}